# Dockerfile.client

FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install the dependencies
RUN npm install --verbose

# Copy the Vue source code
COPY . .

# Build the Vue.js app
RUN npm run build

# Expose the port used by the Vue development server
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev"]
