# Dockerfile.server

FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies for server
COPY ./server/package*.json ./server/
RUN npm install --prefix ./server

# Copy server files
COPY ./server ./server

# Expose port and run server
EXPOSE 5000
CMD ["npm", "run", "start", "--prefix", "./server"]
