services:
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    container_name: express_server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DOMAIN_NAME=http://localhost:5000

  client:
    build:
      context: .
      dockerfile: dockerfile.client
    container_name: vue_client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - server
