version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: express_server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DOMAIN_NAME=${DOMAIN_NAME}

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: vue_client
    ports:
      - "5174:5173"  # Vue default dev port is 5173; mapping to 5174 on localhost
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - server
