# Dockerfile for Express (server)
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Install dotenv to handle environment variables inside the container
RUN npm install dotenv

# Expose the port for the Express server
EXPOSE 5000

# Start the Express server
CMD ["node", "index.js"]
